### ISSUE TITLE
Error when working with system's ruby

### ISSUE THREAD

**Issue by juanmanuelramallo** [rootstrap/rsgem#35]
## Steps to reproduce
1. Linux
2. No ruby version manager
3. `gem install bundler`
4. `gem install rsgem`
5. `rsgem new some_name` 

## Expected
Works correctly

## Actual
```
Traceback (most recent call last):
	9: from /usr/local/bin/rsgem:23:in `<main>'
	8: from /usr/local/bin/rsgem:23:in `load'
	7: from /var/lib/gems/2.7.0/gems/rsgem-0.1.2/exe/rsgem:7:in `<top (required)>'
	6: from /var/lib/gems/2.7.0/gems/dry-cli-0.6.0/lib/dry/cli.rb:67:in `call'
	5: from /var/lib/gems/2.7.0/gems/dry-cli-0.6.0/lib/dry/cli.rb:114:in `perform_registry'
	4: from /var/lib/gems/2.7.0/gems/rsgem-0.1.2/lib/rsgem/cli/commands/new.rb:29:in `call'
	3: from /var/lib/gems/2.7.0/gems/rsgem-0.1.2/lib/rsgem/gem.rb:12:in `create'
	2: from /var/lib/gems/2.7.0/gems/rsgem-0.1.2/lib/rsgem/gem.rb:59:in `create_gem'
	1: from /var/lib/gems/2.7.0/gems/rsgem-0.1.2/lib/rsgem/tasks/create_gem.rb:13:in `create'
/var/lib/gems/2.7.0/gems/rsgem-0.1.2/lib/rsgem/tasks/create_gem.rb:13:in ``': No such file or directory - bundle (Errno::ENOENT)
```

**Comment by juanmanuelramallo** [comment]
Closed by #37
